import {
  Card,
  CardContent,
  CardHeader,
  CardDescription,
  CardTitle,
} from "./ui/card";
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "./ui/empty";
import { CircleNotchIcon, ImageSquareIcon } from "@phosphor-icons/react";
import { AnalysisPanel } from "@/components/AnalysisPanel";
import { VerificationDiff } from "@/components/VerificationDiff";
import type { ImageAuditResult, WorkflowPhase } from "@/lib/types";

interface ImageComparisonProps {
  originalImageUrl: string;
  processedImageUrl: string | null;
  phase: WorkflowPhase;
  preflightAudit: ImageAuditResult | null;
  postflightAudit: ImageAuditResult | null;
  workflowWarnings: string[];
}

export function ImageComparison({
  originalImageUrl,
  processedImageUrl,
  phase,
  preflightAudit,
  postflightAudit,
  workflowWarnings,
}: ImageComparisonProps) {
  const showResultPanel =
    phase === "processing" ||
    phase === "postflight-scanning" ||
    phase === "complete";

  return (
    <div className="flex flex-col gap-4 pb-2">
      <AnalysisPanel audit={preflightAudit} phase={phase} />

      <div className="grid gap-4 md:grid-cols-2 md:gap-5">
        <Card className="bg-card/95 overflow-hidden">
          <CardHeader className="border-b px-4 py-3">
            <CardTitle>Original</CardTitle>
            <CardDescription>
              Source file selected for analysis.
            </CardDescription>
          </CardHeader>
          <CardContent className="bg-muted/35 relative flex h-56 items-center justify-center p-3 sm:h-64 lg:h-[min(48vh,24rem)]">
            <img
              src={originalImageUrl}
              alt="Original"
              className="max-h-full max-w-full object-contain"
            />
          </CardContent>
        </Card>

        {showResultPanel && (
          <Card className="bg-card/95 overflow-hidden">
            <CardHeader className="border-b px-4 py-3">
              <CardTitle>
                {processedImageUrl ? "Processed JPEG" : "Processing"}
              </CardTitle>
              <CardDescription>
                {processedImageUrl
                  ? "Final JPEG generated by the local pipeline."
                  : "The pipeline is preparing the output image."}
              </CardDescription>
            </CardHeader>
            <CardContent className="bg-muted/35 relative flex h-56 items-center justify-center p-3 sm:h-64 lg:h-[min(48vh,24rem)]">
              {processedImageUrl ? (
                <img
                  src={processedImageUrl}
                  alt="Processed"
                  className="max-h-full max-w-full object-contain"
                />
              ) : (
                <Empty className="border">
                  <EmptyHeader>
                    <EmptyMedia variant="icon">
                      {phase === "processing" ||
                      phase === "postflight-scanning" ? (
                        <CircleNotchIcon className="animate-spin" />
                      ) : (
                        <ImageSquareIcon />
                      )}
                    </EmptyMedia>
                    <EmptyTitle>
                      {phase === "postflight-scanning"
                        ? "Verifying output"
                        : "Processing image"}
                    </EmptyTitle>
                    <EmptyDescription>
                      The result appears here as soon as the local workflow
                      finishes.
                    </EmptyDescription>
                  </EmptyHeader>
                </Empty>
              )}
            </CardContent>
          </Card>
        )}
      </div>

      {(phase === "complete" || workflowWarnings.length > 0) && (
        <VerificationDiff
          preflightAudit={preflightAudit}
          postflightAudit={postflightAudit}
          warnings={workflowWarnings}
        />
      )}
    </div>
  );
}
